language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install -e .
before_script:
- python -m spacy download en
- sciwing develop makedirs
- sciwing develop download
script:
- travis_wait 60 pytest -v -p no:warnings tests -m "not slow"
deploy:
  provider: pypi
  user: abhinavkashyap92
  password:
    secure: FEBS1hqcw44tlGoMLzNm3Z6H1kZisubl+Inqnmev2/cuBL8D1v4r4E03bjCj2q4IcRPAhk2527awat0qiMLoR7OYmN6zEZnmZqkc5nx2yqEdlfFlLGVJramB/ALBzleCu4sI81Ns/Mm562UAwb7/AH0ixgyrE/SOmquf1FtL81I0zZcqji4liwPQDfFDDhlwK3kAZ/rz0b0bs3kKmDmR+ErJdJy4v5P1zAYFjYr1MFZwi7GaZhAUN5h90R6f5/nBzrLsCRo3Pi8BrrAOTlMAHB4+IujDW97HZgYEFFoUPJPgJrH8cj1Ck5nMTc71DnGOAw6gcEWejK0HD+Xex2xqZjJHrayOsLi0BK2svZubDnu6W6fMiIQx6Tf5+ltKtrmE/KQlp74vCX93mij/Wz0Dqn4L9fB6QhQiiTuV3XOw17cnpRk8Fw+VeYJm/PDgu+UJYuqo6IjTXLd9HllhpFYldBM0eYicg53CnWcN8ThShWH+HTtBlT5KRr/9f6AIih5Musc4g6rTcYZ354Stsw4A5iVCl/Krgq4kIbNvmrXTc4zhfmU2DyCdG0dPuIv7iElyjOGO8VvvwWVW438gdo90UU9zS+mE/v43E1YTNDSW6rPRs3a4JAckMEdagsQZw5NjTC/grFEu9EezuPD8JVRJpYAygAmEznaPP/+X7VHiDHk=
  on:
    tags: true
    branch: master
